[package]
name = "verplant"
version = "0.1.0"
authors = ["Corin Baurmann <corin.baurmann@gmail.com>", "Matthias Kind <matze.kind@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
